#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck disable=SC1091
source "${ROOT_DIR}/scripts/local-ports.env"

WP="npx wp-env run cli wp"

# Local login: admin / 1234
$WP user update admin --user_pass=1234 --skip-plugins --skip-themes

# Clear stuck maintenance flags from interrupted plugin installs
$WP eval '@unlink(ABSPATH . ".maintenance");'

# Pretty permalinks for headless routing
$WP rewrite structure '/%postname%/' --hard --skip-plugins --skip-themes

# Ensure WPGraphQL is present + active (Faust cannot render without it).
# Dashboard "Update" often fails in wp-env ("could not remove the old plugin") and
# can empty the mounted folder — restore from the release zip without deleting the dir.
WPGRAPHQL_DIR="wp-content/plugins/wp-graphql"
WPGRAPHQL_ZIP_URL="https://downloads.wordpress.org/plugin/wp-graphql.2.20.0.zip"
WPGRAPHQL_VERSION="2.20.0"
NEED_WPGRAPHQL_RESTORE=0
if ! npx wp-env run cli bash -lc "test -f ${WPGRAPHQL_DIR}/wp-graphql.php" >/dev/null 2>&1; then
  NEED_WPGRAPHQL_RESTORE=1
elif ! npx wp-env run cli bash -lc "grep -q \"Version: ${WPGRAPHQL_VERSION}\" ${WPGRAPHQL_DIR}/wp-graphql.php" >/dev/null 2>&1; then
  echo "WPGraphQL is not ${WPGRAPHQL_VERSION}; restoring from release zip..."
  NEED_WPGRAPHQL_RESTORE=1
fi
if [ "${NEED_WPGRAPHQL_RESTORE}" -eq 1 ]; then
  echo "Restoring WPGraphQL ${WPGRAPHQL_VERSION} into ${WPGRAPHQL_DIR}..."
  npx wp-env run cli bash -lc "
    set -e
    TARGET=/var/www/html/${WPGRAPHQL_DIR}
    ZIP=/tmp/wp-graphql-restore.zip
    EXTRACT=/tmp/wp-graphql-restore
    mkdir -p \"\$TARGET\"
    curl -fsSL '${WPGRAPHQL_ZIP_URL}' -o \"\$ZIP\"
    rm -rf \"\$EXTRACT\"
    mkdir -p \"\$EXTRACT\"
    unzip -qo \"\$ZIP\" -d \"\$EXTRACT\"
    SRC=\$(find \"\$EXTRACT\" -type f -name 'wp-graphql.php' | head -1 | xargs dirname)
    find \"\$TARGET\" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
    cp -a \"\$SRC\"/. \"\$TARGET\"/
  "
fi
if ! $WP plugin is-active wp-graphql >/dev/null 2>&1; then
  $WP plugin activate wp-graphql || echo "WARNING: could not activate wp-graphql." >&2
fi

# Dashboard/plugin-zip swaps can leave dependents inactive. Re-activate the
# GraphQL stack Faust and kpf-core need after any restore.
for dep in wp-graphql-content-blocks faustwp.latest-stable faustwp kpf-core wpgraphql-acf; do
  if npx wp-env run cli bash -lc "test -e wp-content/plugins/${dep} || test -e wp-content/plugins/${dep}.php" >/dev/null 2>&1; then
    if ! $WP plugin is-active "${dep}" >/dev/null 2>&1; then
      $WP plugin activate "${dep}" || echo "WARNING: could not activate ${dep}." >&2
    fi
  fi
done

# WPGraphQL: allow Faust generatePossibleTypes
$WP eval 'update_option("graphql_general_settings", array_merge((array) get_option("graphql_general_settings", array()), array("public_introspection_enabled" => "on")));'

# Permanently dismiss WPGraphQL Appsero telemetry toast
$WP eval 'foreach (array("wp-graphql_tracking_notice", "wp-graphql.latest-stable_tracking_notice") as $option) { update_option($option, "hide", false); }'

# Faust: dedicated frontend URL + ensure UUID secret key exists
$WP eval "
use function WPE\FaustWP\Settings\faustwp_update_setting;
use function WPE\FaustWP\Settings\get_secret_key;
use function WPE\FaustWP\Settings\maybe_set_default_settings;

maybe_set_default_settings();
if (!get_secret_key()) {
  faustwp_update_setting('secret_key', wp_generate_uuid4());
}
faustwp_update_setting('frontend_uri', '${KPF_FRONTEND_URL}');
faustwp_update_setting('disable_theme', '1');
# Keep media on the WP domain so admin previews (and content) do not
# point srcset at the Next frontend, which does not serve /wp-content/uploads.
faustwp_update_setting('enable_image_source', '1');
"

# KPF SEO: point public frontend URL at the dedicated local Faust port
$WP eval "
\$settings = get_option('kpf_seo_settings', array());
if (!is_array(\$settings)) {
  \$settings = array();
}
if (!isset(\$settings['global']) || !is_array(\$settings['global'])) {
  \$settings['global'] = array();
}
\$settings['global']['frontend_url'] = '${KPF_FRONTEND_URL}';
update_option('kpf_seo_settings', \$settings, false);
"

# Sync Faust secret + WordPress URL into frontend/.env.local for local Faust.
FAUST_SECRET="$($WP eval 'echo (string) (get_option("faustwp_settings", array())["secret_key"] ?? "");' 2>/dev/null | tr -d '\r' | tail -n 1)"
ENV_LOCAL="${ROOT_DIR}/frontend/.env.local"
{
  echo "# Generated by scripts/wp-bootstrap.sh — do not commit."
  echo "# Ports: admin ${KPF_WP_URL} | frontend ${KPF_FRONTEND_URL}"
  echo "NEXT_PUBLIC_WORDPRESS_URL=${KPF_WP_URL}"
  echo "FAUST_SECRET_KEY=${FAUST_SECRET}"
} > "${ENV_LOCAL}"
echo "Wrote ${ENV_LOCAL}"

# Headless: activate the blank theme WordPress still requires, then remove all others.
if npx wp-env run cli bash -lc 'test -f wp-content/themes/kpf-blank/style.css' >/dev/null 2>&1; then
  $WP theme activate kpf-blank --skip-plugins || echo "WARNING: could not activate kpf-blank." >&2
  INACTIVE_THEMES="$($WP theme list --status=inactive --field=name --skip-plugins 2>/dev/null || true)"
  if [[ -n "${INACTIVE_THEMES}" ]]; then
    # shellcheck disable=SC2086
    $WP theme delete ${INACTIVE_THEMES} --skip-plugins || echo "WARNING: could not delete inactive themes." >&2
  fi
else
  echo "WARNING: kpf-blank theme not mounted yet. Restart wp-env after pulling theme changes." >&2
fi

echo "WordPress bootstrap complete."
echo "Admin login: admin / 1234"
echo "WordPress:  ${KPF_WP_URL}"
echo "WP Admin:   ${KPF_WP_URL}/wp-admin"
echo "Frontend:   ${KPF_FRONTEND_URL}"
echo "Active theme: kpf-blank (headless stub)"
